# Generated by Django 6.0.6 on 2026-06-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='farmers/default.png', upload_to='farmers/'),
        ),
    ]
