# Generated by Django 6.0.6 on 2026-06-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_farmer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='buyers/default.png', upload_to='buyers/'),
        ),
    ]
