# Generated by Django 6.0.6 on 2026-06-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_buyer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
