# Generated by Django 6.0.6 on 2026-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_crop_market_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='ai_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
