# Generated by Django 6.0.6 on 2026-06-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_crop_ai_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
