# Generated by Django 6.0.6 on 2026-06-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='disease_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='leaf_image',
            field=models.ImageField(blank=True, null=True, upload_to='disease/'),
        ),
    ]
