# Generated by Django 6.0.6 on 2026-06-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_crop_disease_report_crop_leaf_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='ai_suggestion',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='disease_report',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='leaf_image',
        ),
    ]
