from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.farmer_register, name='register'),
    path('login/', views.farmer_login, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.farmer_logout, name='logout'),
    path('add_crop/',views.add_crop,name='add_crop'),
    path('crop_list/', views.crop_list, name='crop_list'),
    path('edit_crop/<int:crop_id>/', views.edit_crop, name='edit_crop'),
    path('delete_crop/<int:crop_id>/', views.delete_crop, name='delete_crop'),
    path('buyer_register/', views.buyer_register, name='buyer_register'),
    path('buyer_login/', views.buyer_login, name='buyer_login'),
    path('marketplace/', views.marketplace, name='marketplace'),
    path('crop/<int:crop_id>/', views.crop_detail, name='crop_detail'),
    path('order/<int:crop_id>/', views.place_order, name='place_order'),
    path('farmer-order/', views.farmer_orders, name='farmer_orders'),
    path('accept-order/<int:order_id>/', views.accept_order, name='accept_order'),
    path('reject-order/<int:order_id>/', views.reject_order, name='reject_order'),
    path('buyer-orders/', views.buyer_orders, name='buyer_orders'),
    path('buyer-dashboard/', views.buyer_dashboard, name='buyer_dashboard'),   
    path('farmer-profile/', views.farmer_profile, name='farmer_profile'),
    path('buyer-profile/', views.buyer_profile, name='buyer_profile'),
    path('export-excel/', views.export_excel, name='export_excel'),
    path('export-pdf/', views.export_pdf, name='export_pdf'),
    path('feedback/<int:crop_id>/', views.add_feedback, name='add_feedback'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('edit-buyer-profile/', views.edit_buyer_profile, name='edit_buyer_profile'),
    path('invoice/<int:order_id>/', views.download_invoice, name='download_invoice'),
    path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]
